// Contenido de las tarjetas — tomado de "Volver a empezar en Venezuela · Guía práctica".
// Cada capítulo aporta su versículo y sus dos preguntas de reflexión.
// Cada pregunta se convierte en un día del diario (15 capítulos × 2 = 30 días).

export const chapters = [
  {
    n: 1,
    part: 'Primera parte · El regreso',
    title: 'Los primeros días',
    subtitle: 'Resuelve tres cosas esta semana. Solo tres.',
    verse: 'Sus misericordias son nuevas cada mañana',
    ref: 'Lamentaciones 3:23',
    questions: [
      '¿Qué es lo único que necesito resolver esta semana?',
      '¿Qué estoy tratando de resolver hoy que en realidad puede esperar?',
    ],
    scene: 'avila',
    place: 'El Ávila al amanecer',
    region: 'Caracas',
  },
  {
    n: 2,
    part: 'Primera parte · El regreso',
    title: 'Lo que sientes tiene nombre',
    subtitle: 'No estás mal de la cabeza. Estás de duelo.',
    verse: 'Cercano está el Señor a los quebrantados de corazón',
    ref: 'Salmo 34:18',
    questions: [
      '¿Qué estoy sintiendo hoy que todavía no le he dicho a nadie?',
      '¿Quién en mi vida puede escucharme sin juzgarme?',
    ],
    scene: 'medanos',
    place: 'Médanos de Coro',
    region: 'Falcón',
  },
  {
    n: 3,
    part: 'Primera parte · El regreso',
    title: 'Lo que no perdiste',
    subtitle: 'El inventario que nadie te ayuda a hacer.',
    verse: 'No temas, porque yo estoy contigo',
    ref: 'Isaías 41:10',
    questions: [
      '¿Qué sé hacer hoy que no sabía hacer antes de irme?',
      '¿Qué parte de eso puedo usar esta misma semana?',
    ],
    scene: 'llanos',
    place: 'Los Llanos',
    region: 'Apure',
  },
  {
    n: 4,
    part: 'Segunda parte · Lo práctico',
    title: 'Tus documentos',
    subtitle: 'La llave que abre todo lo demás.',
    verse: 'Esfuérzate y sé valiente; no temas ni desmayes',
    ref: 'Josué 1:9',
    questions: [
      '¿Cuál es el próximo documento que necesito y qué me falta para obtenerlo?',
      '¿Quién puede ayudarme con ese trámite?',
    ],
    scene: 'roraima',
    place: 'Monte Roraima',
    region: 'Gran Sabana, Bolívar',
  },
  {
    n: 5,
    part: 'Segunda parte · Lo práctico',
    title: 'El dinero',
    subtitle: 'Sin capital y sin historial: por dónde arrancar.',
    verse: 'Encomienda al Señor tus obras, y tus proyectos se cumplirán',
    ref: 'Proverbios 16:3',
    questions: [
      '¿Cuánto necesito realmente para vivir un mes?',
      '¿Cuál es la forma más rápida en que puedo generar mi primer ingreso?',
    ],
    scene: 'chuao',
    place: 'Cacaotales de Chuao',
    region: 'Aragua',
  },
  {
    n: 6,
    part: 'Segunda parte · Lo práctico',
    title: 'Un techo',
    subtitle: 'De estar de paso a tener un lugar.',
    verse: 'Edifica tu casa sobre la roca',
    ref: 'Mateo 7:24',
    questions: [
      '¿Qué puedo aportar esta semana en la casa donde estoy?',
      '¿Cuánto necesitaría al mes para tener mi propio espacio?',
    ],
    scene: 'choroni',
    place: 'Pueblo de Choroní',
    region: 'Aragua',
  },
  {
    n: 7,
    part: 'Segunda parte · Lo práctico',
    title: 'El trabajo',
    subtitle: 'Traduce tu experiencia a un trabajo aquí.',
    verse: 'El alma diligente será prosperada',
    ref: 'Proverbios 13:4',
    questions: [
      '¿Qué sé hacer que alguien estaría dispuesto a pagarme esta semana?',
      '¿Cómo voy a responder cuando me pregunten por qué regresé?',
    ],
    scene: 'penero',
    place: 'Peñeros de Juan Griego',
    region: 'Nueva Esparta',
  },
  {
    n: 8,
    part: 'Segunda parte · Lo práctico',
    title: 'Tu salud',
    subtitle: 'El activo que no puedes reponer.',
    verse: 'Yo te devolveré la salud, y sanaré tus heridas',
    ref: 'Jeremías 30:17',
    questions: [
      '¿Qué estoy descuidando de mi salud por resolver otras cosas?',
      '¿Qué puedo hacer hoy mismo para cuidarme, sin gastar dinero?',
    ],
    scene: 'paramo',
    place: 'Páramo de frailejones',
    region: 'Mérida',
  },
  {
    n: 9,
    part: 'Tercera parte · La familia',
    title: 'Los que quedaron allá',
    subtitle: 'Sostén el vínculo aunque estés lejos.',
    verse: 'El Señor vigile entre tú y yo, cuando nos apartemos',
    ref: 'Génesis 31:49',
    questions: [
      '¿Qué horario fijo puedo acordar esta semana para hablar con ellos?',
      '¿Qué les he prometido que no depende de mí?',
    ],
    scene: 'losroques',
    place: 'Archipiélago de Los Roques',
    region: 'Dependencias Federales',
  },
  {
    n: 10,
    part: 'Tercera parte · La familia',
    title: 'Los que te reciben aquí',
    subtitle: 'Gratitud sin quedar atrapado.',
    verse: 'Sobrellevad los unos las cargas de los otros',
    ref: 'Gálatas 6:2',
    questions: [
      '¿Qué conversación he estado evitando con quien me recibió?',
      '¿A quién le debo un gracias dicho de frente?',
    ],
    scene: 'patio',
    place: 'Patio con mango',
    region: 'Casa venezolana',
  },
  {
    n: 11,
    part: 'Tercera parte · La familia',
    title: 'Tu red',
    subtitle: 'Veinte nombres. Cinco cada semana.',
    verse: 'Mejores son dos que uno; si cayeren, el uno levantará a su compañero',
    ref: 'Eclesiastés 4:9',
    questions: [
      '¿A quién voy a escribirle esta semana?',
      '¿Qué puedo ofrecer yo antes de pedir algo?',
    ],
    scene: 'palafitos',
    place: 'Palafitos del Lago',
    region: 'Zulia',
  },
  {
    n: 12,
    part: 'Cuarta parte · Reconstruir',
    title: 'Los primeros noventa días',
    subtitle: 'Noventa días, cuatro etapas, un objetivo por etapa.',
    verse: 'Paso a paso se anda el camino',
    ref: 'Proverbios 4:12 (paráfrasis)',
    questions: [
      '¿En qué etapa de estos noventa días estoy hoy?',
      '¿Qué logré esta semana, por pequeño que parezca?',
    ],
    scene: 'picobolivar',
    place: 'Pico Bolívar',
    region: 'Sierra Nevada, Mérida',
  },
  {
    n: 13,
    part: 'Cuarta parte · Reconstruir',
    title: 'Empezar algo propio',
    subtitle: 'Vende antes de comprar. Esa es la regla.',
    verse: 'Aunque tu comienzo haya sido pequeño, tu final será muy grande',
    ref: 'Job 8:7',
    questions: [
      '¿Qué podría vender o hacer por encargo esta misma semana?',
      '¿Quién sería mi primer cliente, con nombre y apellido?',
    ],
    scene: 'cafetal',
    place: 'Cafetales de Boconó',
    region: 'Trujillo',
  },
  {
    n: 14,
    part: 'Cuarta parte · Reconstruir',
    title: 'Los días malos',
    subtitle: 'Van a venir. Prepárate desde hoy.',
    verse: 'Aunque ande en valle de sombra, no temeré mal alguno',
    ref: 'Salmo 23:4',
    questions: [
      '¿Qué me ayuda cuando estoy en un día malo?',
      '¿A quién puedo llamar ese día, aunque no tenga ganas?',
    ],
    scene: 'nochesabana',
    place: 'Noche en la Gran Sabana',
    region: 'Bolívar',
  },
  {
    n: 15,
    part: 'Cuarta parte · Reconstruir',
    title: 'Mirar adelante',
    subtitle: 'De sobrevivir a construir.',
    verse: 'He aquí que yo hago cosa nueva',
    ref: 'Isaías 43:19',
    questions: [
      '¿Qué quiero que sea distinto dentro de un año?',
      '¿A quién puedo ayudar con lo que ya aprendí?',
    ],
    scene: 'orinoco',
    place: 'Río Orinoco',
    region: 'Delta Amacuro',
  },
];

// 30 días: dos días por capítulo, uno por cada pregunta.
export const days = chapters.flatMap((ch) =>
  ch.questions.map((q, i) => ({
    day: (ch.n - 1) * 2 + i + 1,
    chapter: ch,
    question: q,
    variant: i === 0 ? 'amanecer' : 'tarde',
  }))
);

// Tarjeta de portada.
export const cover = {
  kind: 'cover',
  scene: 'saltoangel',
  variant: 'amanecer',
  place: 'Salto Ángel · Canaima',
  region: 'Bolívar',
  title: 'Volver a empezar',
  title2: 'en Venezuela',
  kicker: 'Diario de 30 días',
  verse: 'He aquí que yo hago cosa nueva',
  ref: 'Isaías 43:19',
  howto: [
    'Una tarjeta por día. No hacen falta treinta minutos: bastan cinco.',
    'Escribe la fecha. Así, dentro de unos meses, vas a poder leer el camino.',
    'Si un día no escribes, no empieces de nuevo: sigue por donde ibas.',
    'Antes de guardarla, anota el paso pequeño de hoy. Lo pequeño es lo que sostiene.',
  ],
};

// Tarjeta de cierre.
export const closing = {
  kind: 'closing',
  scene: 'saltoangel',
  variant: 'tarde',
  place: 'Salto Ángel · Canaima',
  region: 'Bolívar',
  title: 'Lo que logré',
  kicker: 'Cierre · Día 30',
  verse: 'Aunque tu comienzo haya sido pequeño, tu final será muy grande',
  ref: 'Job 8:7',
  checklist: [
    'Documentos en mano',
    'Una línea telefónica mía',
    'Un lugar donde dormir con acuerdo claro',
    'Mi primer ingreso, aunque sea pequeño',
    'Una consulta médica hecha',
    'Horario fijo con los que están lejos',
    'Veinte nombres en mi red',
    'Algo propio empezado',
  ],
};
