/**
 * Generates the static assets the brochure depends on, so that
 * brochure/index.html renders identically offline and in print:
 *
 *   assets/fonts.css   Barlow Condensed + Inter, base64-embedded woff2
 *   assets/qr.svg      real QR code pointing at https://www.okgialfra.com/
 *   assets/world.svg   vector dot-matrix world map (Natural Earth 110m via world-atlas)
 *
 * Run:  node brochure/build-assets.mjs
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import QRCode from 'qrcode'
import { chromium } from 'playwright'
import * as topojson from 'topojson-client'
import world from 'world-atlas/countries-110m.json' with { type: 'json' }

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const OUT = path.join(__dirname, 'assets')
const CHROME = '/opt/pw-browsers/chromium'
fs.mkdirSync(OUT, { recursive: true })

/* ---------------------------------------------------------------- fonts -- */

const FONT_CSS_URL =
  'https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@500;600;700&family=Inter:wght@400;500;600;700&display=swap'
// A modern-browser UA is required or Google serves legacy TTF instead of woff2.
const UA =
  'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'

async function buildFonts() {
  const css = await (await fetch(FONT_CSS_URL, { headers: { 'User-Agent': UA } })).text()

  // Keep only the latin + latin-ext blocks: they cover Spanish accents and the
  // en/em dashes and bullets used throughout, at a fraction of the byte cost.
  const blocks = css.split('/*').filter((b) => /^\s*(latin|latin-ext)\s*\*\//.test(b))
  if (!blocks.length) throw new Error('No latin font blocks found in Google Fonts CSS')

  let out = '/* Generated by build-assets.mjs — do not edit. */\n'
  for (const block of blocks) {
    const body = '/*' + block
    const url = body.match(/url\((https:\/\/fonts\.gstatic\.com\/[^)]+\.woff2)\)/)?.[1]
    if (!url) continue
    const buf = Buffer.from(await (await fetch(url)).arrayBuffer())
    const dataUri = `data:font/woff2;base64,${buf.toString('base64')}`
    out += body.slice(body.indexOf('@font-face')).replace(/url\(https:[^)]+\)/, `url(${dataUri})`)
  }
  fs.writeFileSync(path.join(OUT, 'fonts.css'), out)
  console.log(`fonts.css   ${(out.length / 1024).toFixed(0)} KB (${blocks.length} faces)`)
}

/* ------------------------------------------------------------------- qr -- */

async function buildQR() {
  const svg = await QRCode.toString('https://www.okgialfra.com/', {
    type: 'svg',
    errorCorrectionLevel: 'M',
    margin: 1,
    color: { dark: '#0a1222', light: '#ffffff' },
  })
  fs.writeFileSync(path.join(OUT, 'qr.svg'), svg)
  console.log('qr.svg      https://www.okgialfra.com/')
}

/* ------------------------------------------------------------ world map -- */

// Equirectangular frame. Antarctica and the high Arctic are cropped so the
// inhabited landmasses fill the plate instead of floating in empty ocean.
const W = 1000
const H = 460
const LON0 = -168
const LON1 = 190
const LAT0 = 79
const LAT1 = -57
const STEP = 5 // dot pitch in map units
const R = 1.45 // dot radius

async function buildWorldMap() {
  const land = topojson.feature(world, world.objects.countries)

  // Rasterise the land polygons once in Chromium, then read the pixel mask
  // back and re-emit it as vector dots — crisp at any print resolution.
  const browser = await chromium.launch({ executablePath: CHROME })
  const page = await browser.newPage({ viewport: { width: W, height: H } })
  const mask = await page.evaluate(
    ({ geo, b }) => {
      const px = ([lon, lat]) => [
        ((lon - b.LON0) / (b.LON1 - b.LON0)) * b.W,
        ((b.LAT0 - lat) / (b.LAT0 - b.LAT1)) * b.H,
      ]
      const cv = document.createElement('canvas')
      cv.width = b.W
      cv.height = b.H
      const ctx = cv.getContext('2d')
      ctx.fillStyle = '#fff'

      // Each polygon is filled on its own path. Accumulating every country into
      // a single even-odd path would make shared borders cancel out.
      //
      // Rings that cross the antimeridian (Russia's Chukotka, Fiji) jump from
      // +179 to -179, which projects into a band sweeping the whole plate. The
      // ring is therefore "unwrapped" into a continuous longitude run, then
      // drawn at -360/0/+360 so whichever copy lands inside the window shows.
      const drawPoly = (poly, shift) => {
        ctx.beginPath()
        for (const r of poly) {
          let prev = null
          r.forEach((p, i) => {
            let lon = p[0]
            if (prev !== null) {
              while (lon - prev > 180) lon -= 360
              while (lon - prev < -180) lon += 360
            }
            prev = lon
            const [x, y] = px([lon + shift, p[1]])
            i ? ctx.lineTo(x, y) : ctx.moveTo(x, y)
          })
          ctx.closePath()
        }
        ctx.fill('evenodd') // even-odd within one polygon = interior holes
      }

      for (const f of geo.features) {
        const polys = f.geometry.type === 'Polygon' ? [f.geometry.coordinates] : f.geometry.coordinates
        for (const poly of polys) for (const shift of [-360, 0, 360]) drawPoly(poly, shift)
      }
      const d = ctx.getImageData(0, 0, b.W, b.H).data
      const bits = []
      for (let i = 0; i < d.length; i += 4) bits.push(d[i + 3] > 40 ? 1 : 0)
      return bits
    },
    { geo: land, b: { W, H, LON0, LON1, LAT0, LAT1 } }
  )
  await browser.close()

  const at = (x, y) => {
    const xi = Math.round(x)
    const yi = Math.round(y)
    if (xi < 0 || xi >= W || yi < 0 || yi >= H) return false
    return mask[yi * W + xi] === 1
  }
  let dots = ''
  let n = 0
  for (let y = STEP / 2; y < H; y += STEP) {
    for (let x = STEP / 2; x < W; x += STEP) {
      if (!at(x, y)) continue
      // Coastal dots sit slightly brighter, which gives the plate its relief.
      const edge = !at(x - STEP, y) || !at(x + STEP, y) || !at(x, y - STEP) || !at(x, y + STEP)
      dots += `<circle cx="${x.toFixed(1)}" cy="${y.toFixed(1)}" r="${R}"${edge ? ' class="e"' : ''}/>`
      n++
    }
  }

  // Colours are baked in so the plate can be dropped in as a plain <img>.
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" width="${W}" height="${H}">
<style>circle{fill:#22375c}circle.e{fill:#3d6199}</style>
<g>${dots}</g>
</svg>`
  fs.writeFileSync(path.join(OUT, 'world.svg'), svg)
  console.log(`world.svg   ${n} dots`)
  return { W, H, LON0, LON1, LAT0, LAT1 }
}

await buildFonts()
await buildQR()
await buildWorldMap()
console.log('\nAssets written to brochure/assets/')
